openapi: 3.0.0
servers:
  - url: 'http://localhost/master-data/0.0.1'
info:
  version: "0.0.1-oas3"
  title: Master Data
  description: API for managing master data
paths:
  /address:
    get:
      summary: Retrieve addresses using OData queries
      description: ''
      parameters: [ 
        {
          $ref: 'https://raw.githubusercontent.com/johnathanesanders/definitions-openapi/master/schema/odata/parameters.json#/count'
        },
        {
          $ref: 'https://raw.githubusercontent.com/johnathanesanders/definitions-openapi/master/schema/odata/parameters.json#/filter'
        },
        {
          $ref: 'https://raw.githubusercontent.com/johnathanesanders/definitions-openapi/master/schema/odata/parameters.json#/search'
        },
        {
          $ref: 'https://raw.githubusercontent.com/johnathanesanders/definitions-openapi/master/schema/odata/parameters.json#/skip' 
        },
        {
          $ref: 'https://raw.githubusercontent.com/johnathanesanders/definitions-openapi/master/schema/odata/parameters.json#/top'
        }  
      ]
      responses:
        '200':
          description: 'OK'
          content: 
            application/json:
              schema: 
                type: array
                items:
                  $ref: 'https://raw.githubusercontent.com/johnathanesanders/definitions-openapi/master/schema/common/Address.json'
        '404':
          description: Address not found
      security: []
